### ISSUE TITLE
Premature exception being thrown

### ISSUE THREAD

**Issue by momalenga** [afzalali15/http_client#1]
https://github.com/afzalali15/http_client/blob/f1527c2233408529e4585a1a3e6e2e0d8bb98d18/lib/services/base_client.dart#L29

I think you have a problem there. It might need to be something like this?

 return _processResponse(response);
    } on BadRequestException {

**Comment by afzalali15** [comment]
You are right, I was demonstrating BadRequest and committed the same code 😄 
made the changes 👍
